### ISSUE TITLE
A7RIVa version 

### ISSUE THREAD

**Issue by astrohunt98** [dougforpres/SonyCamera#12]
Hi there, I’m glad I’ve been able to find your fix but my camera version isn’t supported yet. Could you please add it.?
Thanks so much for publishing this fix, I thought I wasn’t going to be able to use all the equipment I just bought.

**Comment by dougforpres** [comment]
The library auto-supports any newly detected camera (after running the SonyCameraInfo tool.
The tool outputs info about the camera so it can be added into the library such that future users won't have to "learn" the camera using SonyCameraInfo.
