### ISSUE TITLE
Add BAYERPAT to FITS

### ISSUE THREAD

**Issue by Linwood-F** [dougforpres/SonyCamera#9]
I'm not really sure fi this belongs here, the ASCOM driver.  Is it possible to add to the FITS header as it gets conveyed into applications like APT the BAYERPAT key and value RGGB?

Programs like Pixinsight can figure that out for raw (ie. ARW) files, but once they are conveyed into FITS and passed on in turn to a post processing program, it does not know.  I've manually added BAYERPAT=RGGB and this seems to fix it.

I think technically adding XBAYROFF=0 and YBAYROFF=0 would be correct but they appear to default to zero.   All I had to add to get Pixinsight to work fine was BAYERPAT.

**Comment by Linwood-F** [comment]
This may (or may not) be relevant to this.  I finally got NINA working and NINA is storing BAYERPAT where APT does not.  Maybe it is figuring it out, not sure.

**Comment by dougforpres** [comment]
Sorry for the delay in responding - didn't see these issues pop up.

The ASCOM "standard" doesn't really allow for that info to be passed to the app.  In fact, that's why APT has the Debayer Pattern drop-down in the camera-connect dialog.

It would be great if APT pushed that into the FITS file.  I'd suggest pinging Yoddha @ https://aptforum.com/phpbb/viewforum.php?f=17

Doug

**Comment by dougforpres** [comment]
@Linwood-F - If you're still interested, I got a reply when asking on the APT forum - apparently the BAYERPAT header can be added, it's just a setting

https://aptforum.com/phpbb/viewtopic.php?f=17&t=3850

**Comment by Linwood-F** [comment]
Thanks.  I'm probably converting to NINA now that I have a 64 bit driver, but I did experiment with this.  Setting that field won't do it, you also have to enable the preview debayer option, which both adds time to shots.  The good news is the FIT file isn't debayered, so it's a viable workaround. But thanks, it would have certainly helped.
